stages:
  train:
    cmd: python source/train.py
    deps:
    - data/test/
    - source/train.py
    - source/model.py
    - source/preprocess.py
    params:
    - general.random_seed
    - train.learning_rate
    - train.epochs
    outs:
    - models