stages:
  train:
    cmd: python source/train.py
    deps:
    - data/processed/
    - source/train.py
    - source/model.py
    - source/preprocess.py
    params:
    - general.random_seed
    - train.learning_rate
    - train.epochs
    outs:
    - models
  save_logs:
    cmd: python source/utils/logs.py
    deps:
    - source/utils/logs.py
    outs:
    - exp_logs/