stages:
  train:
    cmd: python source/train.py
    deps:
    - data/processed/
    - source/train.py
    - source/model.py
    - source/preprocess.py
    params:
    - general.random_seed
    - preprocess.min_split_ratio
    - model.conv2d_dilation
    - train.device_request
    - train.batch_size
    - train.learning_rate
    - train.epochs
    - train.early_stopping_patience
    - train.weight_scaling
    outs:
    - models
  save_logs:
    cmd: python source/utils/logs.py
    deps:
    - source/utils/logs.py
    outs:
    - exp_logs/