general:
  random_seed: 42
preprocess:
  min_split_ratio: 0.75
model:
  conv2d_dilation: 1
train:
  device_request: 'cuda'
  batch_size: 128
  learning_rate: 0.0005
  epochs: 10
  early_stopping_patience: 5