general:
  random_seed: 42
preprocess:
  min_split_ratio: 0.75
model:
  conv2d_dilation: 1
train:
  device_request: cuda
  batch_size: 128
  learning_rate: 5e-05
  epochs: 10
  early_stopping_patience: 5
  weight_scaling: 0.5
